<?php

declare(strict_types=1);

return [
    'legacy_root' => dirname(__DIR__) . '/htdocs',
    'front_controller' => 'index.php',
    'laravel_paths' => [
        'up',
    ],
    'asset_extensions' => [
        'avif',
        'bmp',
        'css',
        'csv',
        'gif',
        'html',
        'ico',
        'jpeg',
        'jpg',
        'js',
        'json',
        'map',
        'mjs',
        'otf',
        'png',
        'svg',
        'txt',
        'webm',
        'webp',
        'woff',
        'woff2',
        'xml',
    ],
    'mime_types' => [
        'avif' => 'image/avif',
        'bmp' => 'image/bmp',
        'css' => 'text/css; charset=UTF-8',
        'csv' => 'text/csv; charset=UTF-8',
        'gif' => 'image/gif',
        'html' => 'text/html; charset=UTF-8',
        'ico' => 'image/x-icon',
        'jpeg' => 'image/jpeg',
        'jpg' => 'image/jpeg',
        'js' => 'application/javascript; charset=UTF-8',
        'json' => 'application/json; charset=UTF-8',
        'map' => 'application/json; charset=UTF-8',
        'mjs' => 'application/javascript; charset=UTF-8',
        'otf' => 'font/otf',
        'png' => 'image/png',
        'svg' => 'image/svg+xml',
        'txt' => 'text/plain; charset=UTF-8',
        'webm' => 'video/webm',
        'webp' => 'image/webp',
        'woff' => 'font/woff',
        'woff2' => 'font/woff2',
        'xml' => 'application/xml; charset=UTF-8',
    ],
];
