name: Rector

on:
  pull_request:
    paths:
      - '**/*.php'

jobs:
  rector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # Execute Rector using existing action
      - name: Run Rector
        uses: zingimmick/rector-action@0.0.3

      # Commit & pushthe changes back to the PR branch
      - name: Commit & Push Rector changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          message: "chore: apply Rector PSR-12"
